In [2]:
set1:set = {1,1,3,3,5,8,7,9,10}
set1.add(11)

for value in set1:
    print(value)


1
3
5
7
8
9
10
11


In [3]:
#需要先在終端機安裝pip install numpy
#更新指令pip install --upgrade numpy
import numpy as np

array1:np.ndarray = np.array(range(1,11))

#陣列運算
array1 + 10 * 50

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510])

In [4]:
display(np.arange(1.3,3.5,0.1))
display(np.linspace(1,2,20))

array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [5]:
display(np.random.random())
display(np.random.randn(10,5,3))
display(np.random.randint(1,10,size=(10,5)))

0.2667936781040192

array([[[ 2.49444589e-01,  4.94576136e-01,  2.03234044e-01],
        [ 6.82015323e-01, -1.04754689e-01, -4.20393010e-01],
        [ 5.05362692e-01,  1.05112731e+00, -6.31602969e-02],
        [ 8.71117365e-01, -8.97860436e-01, -5.27118984e-01],
        [-9.47475924e-01, -1.01384489e-01, -8.05335082e-01]],

       [[-1.50199426e+00,  4.32300147e-01,  6.53911648e-01],
        [-7.08183374e-02, -3.77295081e-01, -6.98651793e-01],
        [-1.61220457e-01,  3.85830818e-01, -1.31910611e-01],
        [ 4.87627543e-02,  4.47370210e-01, -6.14401032e-01],
        [-6.38880483e-01, -2.16274363e-01,  1.06015451e-01]],

       [[ 7.76980226e-01, -1.91258761e+00,  1.38993593e+00],
        [-1.73377998e+00, -3.07746186e-01,  1.04013722e+00],
        [-6.27345292e-01, -1.00508796e+00,  9.32246104e-01],
        [-8.20331703e-02,  1.68276428e+00,  1.33696405e+00],
        [-1.31707082e+00, -2.82263961e-02,  7.85298018e-01]],

       [[-4.92428664e-01, -3.90824138e-01, -5.06230940e-01],
        [ 1.316052

array([[5, 9, 1, 6, 1],
       [3, 1, 8, 2, 1],
       [6, 6, 8, 7, 1],
       [6, 5, 3, 8, 4],
       [6, 8, 7, 5, 3],
       [9, 9, 6, 7, 7],
       [4, 3, 6, 1, 9],
       [2, 5, 4, 7, 1],
       [3, 5, 1, 9, 8],
       [3, 3, 9, 3, 8]])